GET_CONNECT            05
PUSH_CONNECT           10
GET_DISCONNECT         15
PUSH_DISCONNECT        20
GET_INFO_MAZES         25
PUSH_INFO_MAZES        30
GET_SELECTED_MAZE      35
GET_MAZE               40
PUSH_MAZE              45
PUSH_LINE              50
GET_REC                55
PUSH_REC               60
GET_MOVE               65
PUSH_MOVE              70
GET_HIST_MAZE          75
GET_HIST_PLAYER        80
PUSH_HIST              85
GET_CHALLENGE          90
GET_MESSAGE            95
PUSH_MESSAGE          100
GET_ENDED_GAME        105
PUSH_ENDED_GAME       110
GET_CHALLENGERS       115
PUSH_CHALLENGERS      120
GET_JOIN              125
GET_WINNER            130
PUSH_WINNER           135
ERROR_PROTOCOL        140
